version: '3'

services:
  caddy:
    image: caddy
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - 80:80
      - 443:443
    command: caddy reverse-proxy --from $WG_DOMAIN --to wg-easy:51821

  wg-easy:
    image: weejewel/wg-easy
    container_name: wg-easy
    environment:
      - WG_HOST=$WG_HOST
      - PASSWORD=$WG_PASSWORD
      - WG_MTU=1296
    volumes:
      - ./data/wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped

  swgp:
    image: swgp:latest
    container_name: swgp-go
    ports:
      - "20220:20220/udp"
    volumes:
      - ./swgp_server.conf:/etc/swgp/server.conf
    restart: unless-stopped

networks:
  default:
    external:
      name: caddy_net

volumes:
  caddy_data:
  caddy_config:
